- name: Run Kumo-Discord Docker container
  hosts: SC-EVIE
  vars:
    discord_token: xxx
    image: git.kurumi.at/shinkuri/kumo-discord
  tasks:
    - name: Pull Docker image
      docker_image:
        name: {{ image }}
        source: pull
        force_source: yes
        state: present

    - name: Run container
      docker_container:
        name: Kumo-Discord
        image: {{ image }}
        env:
          DISCORD_TOKEN: "{{ discord_token }}"
          GUILD_ID: "136661702287556608"
        state: started
