- name: Run Kumo-Discord Docker container
  hosts: SC-EVIE
  tasks:
    - name: Pull Docker image
      docker_image:
        name: git.kurumi.at/shinkuri/kumo-discord
        state: present

    - name: Run container
      docker_container:
        name: Kumo-Discord
        image: git.kurumi.at/shinkuri/kumo-discord
        env:
          - "DISCORD_TOKEN:{{discord_token}}"
          - "GUILD_ID:136661702287556608`"
        state: started